// Arlo Emerson, 10/1/2018
// arloemerson@gmail.com

// clean up the project by removing comps that were auto-generated by the Pixel 3 scripts

// Added functionality to Array object as Adobe does implement modern javascript
if(!Array.prototype.indexOf) 
{
    Array.prototype.indexOf = function(obj) 
    {
        for(var i=0; i<this.length; i++) 
        {
            if(obj===this[i])
            {
                return i;
            }
        }
        return -1;
    };
}

start();

function start() 
{
    app.beginUndoGroup("dm_render");
    
    if (app.project != null) 
    {        
        var allComps = app.project.items;                                          
        var removedCount = 0;

        for (var i = allComps.length; i >= 1; i--) 
        {
            item = allComps[i];
            if ( item.name.indexOf("remove after render") > -1 )
            {
                item.remove();
                removedCount++;
            }
        }

        alert(removedCount + " item/s were removed. You can undo if needed.");
    }

    app.endUndoGroup(); 
}


    
